name: Integrated Fund Analysis Workflow

on:
  schedule:
    - cron: '0 9 * * *'  # 每天北京时间17:00运行（UTC+8为9:00 UTC）
  workflow_dispatch:  # 支持手动触发

jobs:
  analyze-funds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 与现有脚本兼容，可调整为 3.8 或其他

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium chromium-driver
          sudo ln -s /usr/lib/chromium/chromedriver /usr/bin/chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests akshare selenium tenacity beautifulsoup4 lxml openpyxl scrapy html5lib tabulate glob3 urllib3 schedule firebase-admin

      - name: Run integrate_fund_rank.py
        run: python integrate_fund_rank.py
        env:
          TZ: Asia/Shanghai  # 北京时间

      - name: Commit and push results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add result_*.txt recommended_cn_funds.csv analysis_report.md market_monitor_report.md data/*.csv fund_rank_integrate.log
          git commit -m "Update fund analysis results for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fund-reports
          path: |
            result_*.txt
            recommended_cn_funds.csv
            analysis_report.md
            market_monitor_report.md
            data/*.csv
            fund_rank_integrate.log
